import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import json

datadir = "/home/claude/hx_project/data"
outdir = "/home/claude/hx_project/outputs"

with open(f"{datadir}/design_comparison.json") as f:
    C = json.load(f)
with open(f"{datadir}/process_spec.json") as f:
    P = json.load(f)
opt = C["optimized"]

do = P["do_m"]; pt = opt["pt"]; Nt = opt["Nt"]; Ds = opt["Ds"]; Db = opt["Db"]
passes = opt["passes"]; layout = opt["layout"]

# ----------------------------------------------------------------------
# 1. Tube bundle cross-section (triangular pitch, generated by packing
#    rings of tubes on a triangular lattice out to the bundle diameter)
# ----------------------------------------------------------------------
pts = []
row_spacing = pt*np.sqrt(3)/2
n_rows = int(np.ceil(Db/row_spacing)) + 2
for r in range(-n_rows, n_rows+1):
    y = r*row_spacing
    x_offset = (pt/2) if (r % 2 != 0) else 0.0
    n_cols = int(np.ceil(Db/pt)) + 2
    for c in range(-n_cols, n_cols+1):
        x = c*pt + x_offset
        if x**2 + y**2 <= (Db/2)**2:
            pts.append((x, y))
pts = np.array(pts)
# trim/pad to match Nt as closely as possible (keep the Nt closest to center)
dist = np.sqrt(pts[:,0]**2 + pts[:,1]**2)
order = np.argsort(dist)
pts = pts[order][:Nt]

fig, ax = plt.subplots(figsize=(6.5, 6.5))
shell_circle = plt.Circle((0,0), Ds/2*1000, fill=False, color="k", linewidth=2)
bundle_circle = plt.Circle((0,0), Db/2*1000, fill=False, color="gray", linewidth=1, linestyle="--")
ax.add_patch(shell_circle); ax.add_patch(bundle_circle)
for i, (x, y) in enumerate(pts):
    pass_id = 0 if x <= 0 else 1   # simple pass split for 2-pass illustration
    color = "#1f4e79" if pass_id == 0 else "#c0392b"
    ax.add_patch(plt.Circle((x*1000, y*1000), do/2*1000, color=color))
ax.axvline(0, color="gray", linestyle=":", linewidth=1)
ax.set_xlim(-Ds/2*1200, Ds/2*1200); ax.set_ylim(-Ds/2*1200, Ds/2*1200)
ax.set_aspect("equal")
ax.set_title(f"Tube Bundle Layout \u2014 Optimized Design\n"
             f"{Nt} tubes, {layout} pitch {pt*1000:.1f} mm, {passes} passes, "
             f"Shell ID {Ds*1000:.0f} mm")
ax.set_xlabel("mm"); ax.set_ylabel("mm")
legend_elems = [mpatches.Patch(color="#1f4e79", label="Pass 1"),
                mpatches.Patch(color="#c0392b", label="Pass 2")]
ax.legend(handles=legend_elems, loc="upper right")
plt.tight_layout()
plt.savefig(f"{outdir}/08_tube_bundle_layout.png")
plt.close()
print(f"Tube bundle layout saved ({len(pts)} tubes placed vs Nt={Nt} target)")

# ----------------------------------------------------------------------
# 2. Longitudinal schematic: shell, baffles, nozzles
# ----------------------------------------------------------------------
L = P["L_tube_m"]
Nb = int(round(opt["Nb"]))
B = opt["B"]
baffle_x = np.linspace(0, L, Nb+2)[1:-1]

fig, ax = plt.subplots(figsize=(10, 4.2))
# shell
ax.add_patch(mpatches.Rectangle((0, -Ds/2*1000), L*1000, Ds*1000,
                                 facecolor="#dce6f0", edgecolor="k", linewidth=1.5))
# tube bundle (as a band)
ax.add_patch(mpatches.Rectangle((0, -Db/2*1000), L*1000, Db*1000,
                                 facecolor="#f2e6c8", edgecolor="none", alpha=0.6))
# baffles (alternating up/down segmental cut, 25%)
cut = 0.25
for i, bx in enumerate(baffle_x):
    if i % 2 == 0:
        y0, y1 = -Ds/2*1000, (Ds/2 - cut*Ds)*1000
    else:
        y0, y1 = (-Ds/2 + cut*Ds)*1000, Ds/2*1000
    ax.plot([bx*1000, bx*1000], [y0, y1], color="#c0392b", linewidth=2)

# nozzles
ax.annotate("Hot oil IN\n(150\u00b0C)", xy=(L*1000, 0), xytext=(L*1000+30, Ds/2*1000+40),
            fontsize=8, ha="center", arrowprops=dict(arrowstyle="->"))
ax.annotate("Hot oil OUT\n(100\u00b0C)", xy=(0, 0), xytext=(-60, Ds/2*1000+40),
            fontsize=8, ha="center", arrowprops=dict(arrowstyle="->"))
ax.annotate("Cold water\nIN (30\u00b0C)", xy=(0, -Ds/2*1000), xytext=(-60, -Ds/2*1000-60),
            fontsize=8, ha="center", arrowprops=dict(arrowstyle="->"))
ax.annotate("Cold water\nOUT (70\u00b0C)", xy=(L*1000, -Ds/2*1000), xytext=(L*1000+30, -Ds/2*1000-60),
            fontsize=8, ha="center", arrowprops=dict(arrowstyle="->"))

ax.set_xlim(-120, L*1000+120)
ax.set_ylim(-Ds/2*1000-120, Ds/2*1000+120)
ax.set_aspect("equal")
ax.set_title(f"Shell-and-Tube HX \u2014 Longitudinal Schematic (Optimized Design)\n"
             f"Shell ID {Ds*1000:.0f} mm, {Nb} baffles @ {B*1000:.0f} mm spacing, "
             f"1 shell pass / {passes} tube passes")
ax.set_xlabel("mm"); ax.set_ylabel("mm")
plt.tight_layout()
plt.savefig(f"{outdir}/09_longitudinal_schematic.png")
plt.close()
print("Longitudinal schematic saved")
